# Generated by Django 3.1.7 on 2021-04-07 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='professors.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professors.groups')),
            ],
        ),
        migrations.CreateModel(
            name='UsersXProfessors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z1', models.CharField(default='0', max_length=1)),
                ('z2', models.CharField(default='0', max_length=1)),
                ('z3', models.CharField(default='0', max_length=1)),
                ('z4', models.CharField(default='0', max_length=1)),
                ('z5', models.CharField(default='0', max_length=1)),
                ('z6', models.CharField(default='0', max_length=1)),
                ('z7', models.CharField(default='0', max_length=1)),
                ('z8', models.CharField(default='0', max_length=1)),
                ('z9', models.CharField(default='0', max_length=1)),
                ('z10', models.CharField(default='0', max_length=1)),
                ('sum', models.CharField(default='0', max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.students')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='lector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lector', to='professors.professors'),
        ),
        migrations.AddField(
            model_name='groups',
            name='seminarist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminarist', to='professors.professors'),
        ),
    ]
