# Generated by Django 3.1.7 on 2021-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sum',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='z1',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z10',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z2',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z3',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z4',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z5',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z6',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z7',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z8',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='z9',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
