# Generated by Django 3.1.7 on 2021-03-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_tests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='student_id',
            new_name='student',
        ),
    ]
