# Generated by Django 3.1.7 on 2021-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_auto_20210321_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='b',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='a',
            new_name='z1',
        ),
        migrations.AddField(
            model_name='tests',
            name='z10',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z2',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z3',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z4',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z5',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z6',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z7',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z8',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tests',
            name='z9',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
