# Generated by Django 3.1.7 on 2021-03-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_auto_20210330_2057'),
    ]

    operations = [
    ]
