# Generated by Django 3.1.7 on 2021-03-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0010_auto_20210330_2206'),
    ]

    operations = [

        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lector_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lector', to='professors.professors')),
                ('seminarist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminarist', to='professors.professors')),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professors.groups'),
        ),
    ]
