# Generated by Django 3.1.7 on 2021-03-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_auto_20210330_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='lector_id',
            new_name='lector',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='seminarist_id',
            new_name='seminarist',
        ),
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
