# Generated by Django 3.1.7 on 2021-03-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0012_auto_20210330_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
