# Generated by Django 3.1.7 on 2021-03-30 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0013_professortypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='z1',
            field=models.CharField(default='0', max_length=1, validators=[django.core.validators.RegexValidator('/[0-2]/')]),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z10',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z2',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z3',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z4',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z5',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z6',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z7',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z8',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tests',
            name='z9',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
