# Generated by Django 3.1.7 on 2021-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0014_auto_20210331_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='z1',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
