# Generated by Django 3.1.7 on 2021-04-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0015_auto_20210406_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='professors.discipline'),
        ),
    ]
